from elasticsearch import Elasticsearch
import csv

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "elastic"

es_client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="../certs/ca/ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

print(
    f"Connected to ElasticSearch cluster `{es_client.info().body['cluster_name']}`")

with open("./car-data-example/Car details v3.csv", "r") as f:
    reader = csv.reader(f)

    for i, line in enumerate(reader):
        document = {
            "name": line[0],
            "engine": line[9],
            "year": line[1],
            "price": line[2],
        }
        es_client.index(index="cars", document=document)
